### ISSUE TITLE
Cannot install with package.el on Emacs 24.4

### ISSUE THREAD

**Issue by hydandata** [sshirokov/ZNC.el#15]
`package-compute-transaction: Package `erc-5.3' is unavailable` it seems to have gone from MELPA/Marmalade/GNU package repositories.

**Comment by alezost** [comment]
I'm not sure but perhaps this happens because "erc.el" does not contain `Version:` field in its header.
Anyway I believe it would be better to exclude `(erc "5.3")` from ["Package-Requires:" line](https://github.com/sshirokov/ZNC.el/blob/master/znc.el#L7), since `erc` has been a part of Emacs for a long time.
It will fix this issue.

**Comment by seanfarley** [comment]
I just created a pull request to fix this issue since I just stumbled upon it as well. Let's hope it gets merged soon.

**Comment by milkypostman** [comment]
see milkypostman/melpa#2824

**Comment by sshirokov** [comment]
This is actually closed by https://github.com/sshirokov/ZNC.el/pull/19
